spring:
    profiles:
      active: dev
    thymeleaf:
      cache: false
      mode: LEGACYHTML5
    http:
      encoding:
        force: true
      multipart:
        max-request-size: 1024MB
        max-file-size: 1024MB
    cache:
      type: redis
    mvc:
      favicon:
        enabled: false
logging:
  level: debug
mybatis:
  configuration:
    log-prefix: dao.*
server:
  context-path: /WebProject
  use-forward-headers: true